services:
  parser:
    build:
      context: .
      target: runtime           # <-- запускаем именно runtime-стадию
    container_name: parser
    restart: unless-stopped
    env_file: .env  # Добавляем эту строку
    ports:
      - '8000:8000'
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/${MONGO_DB}?authSource=parserDB
      PORT: 8000
    volumes:
      - ./failed_captchas:/usr/src/app/failed_captchas
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: parserDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data:
